### ISSUE TITLE
Ensure the result works with the u flag

### ISSUE THREAD

**Issue by domenic** [tc39/proposal-regex-escaping#52]
I recently enabled the ESLint rule which encourages always using the `u` flag. When doing so, I found out that my custom regexp escaper, which was

```js
function escapeRegExp(str) {
  return str.replace(/[-[\]/{}()*+?.\\^$|]/ug, "\\$&");
}
```

was overzealous, and would cause `new RegExp(escapeRegExp(input), "ug")` to fail when the input string contained a `-`.

This probably has some intersection with discussions in other threads, e.g. if some delegates require that the result escape `-` so that it can work in situations like `new RegExp("[" + RegExp.escape(input) + "]", "ug")`, such a requirement prohibits the result from working in situations like `new RegExp(RegExp.escape(input), "ug")`.

**Comment by bakkot** [comment]
Yeah, as I [suggested in that thread](https://github.com/tc39-transfer/proposal-regex-escaping/issues/48#issuecomment-769450691), I think if we include `-` in this proposal we'd need to change `u`-mode regexes so that `\-` is treated an identity escape, i.e. it maps to `-` .
