### ISSUE TITLE
Motivation for the current set of escaped characters

### ISSUE THREAD

**Issue by zloirock** [tc39/proposal-regex-escaping#59]
The sets of escaped characters in [the spec draft](https://tc39.es/proposal-regex-escaping/) and in [the motivation section](https://github.com/tc39/proposal-regex-escaping/blob/main/EscapedChars.md) differ significantly. Maybe makes sense to explain the current choice and update docs?

**Comment by ljharb** [comment]
Indeed; i haven’t updated the readme yet since yesterday.
