### ISSUE TITLE
editorial: _escapedList_ mixes code units and code points

### ISSUE THREAD

**Issue by michaelficarra** [tc39/proposal-regex-escaping#68]
It'd probably be best to create a string through repeated string-concatenations and call UTF16EncodeCodePoint directly.

**Comment by ljharb** [comment]
Good catch.

Your suggestion tho seems more complex than either converting the code units into code points while adding them, for example.

**Comment by ljharb** [comment]
I think that this is fixed by #67. Will reopen if not.
