### ISSUE TITLE
Advance to stage 2

### ISSUE THREAD

**Issue by benjamingr** [tc39/proposal-regex-escaping#9]
From [the tc39 process](https://docs.google.com/document/d/1QbEE0BsO4lvl7NFTn5WXWeiEIBfaVUF7Dk0hpPpPDzU/edit):
- [x] Step 1 Criteria
- [x] Initial spec text

Available at http://benjamingr.github.io/RexExp.escape/ and at the readme file.
- [x] tc39 approval of the advancement of the spec to the next level.

**Comment by ljharb** [comment]
Done. https://github.com/tc39/proposals/commit/cc2b37dcdbe378539d54b6901577ec5c2888fd3d
